apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hub-ingress
  namespace: bomberman
spec:
  ingressClassName: public
  rules:
  - host: hub.bomberman.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hub-api
            port:
              number: 80