apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-tcp-config
  namespace: bomberman
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    
    stream {
        # Test iniziale con una room fissa
        server {
            listen 10001;
            proxy_pass test-room-svc.bomberman.svc.cluster.local:80;
        }
    }