apiVersion: v1
kind: Service
metadata:
  name: nginx-tcp-proxy
  namespace: bomberman
spec:
  type: NodePort
  selector:
    app: nginx-tcp-proxy
  ports:
    - name: room-10001
      port: 10001
      targetPort: 10001
      nodePort: 30001