apiVersion: v1
kind: Pod
metadata:
  name: test-room
  namespace: bomberman
  labels:
    app: test-room
spec:
  containers:
    - name: apache
      image: httpd:2.4
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: test-room-svc
  namespace: bomberman
spec:
  selector:
    app: test-room
  ports:
    - port: 80
      targetPort: 80